use anyhow::{Context, Result};
use colored::Colorize;
use std::path::PathBuf;

const SERVICE_NAME: &str = "app-dist";
const KEYCHAIN_USER: &str = "api-key";

pub struct Config {
    pub api_url: String,
    pub api_key: Option<String>,
    pub config_path: PathBuf,
}

impl Config {
    pub fn load(api_url_override: Option<&str>) -> Result<Self> {
        let config_dir = dirs::config_dir()
            .context("Could not determine config directory")?
            .join("app-dist");
        std::fs::create_dir_all(&config_dir).ok();

        let config_path = config_dir.join("app-dist.yml");

        let api_url = if let Some(url) = api_url_override {
            url.to_string()
        } else {
            std::env::var("APP_DIST_API_URL")
                .unwrap_or_else(|_| "https://api.app-dist.com".to_string())
        };

        let api_key = get_keychain_key().ok();

        Ok(Self {
            api_url,
            api_key,
            config_path,
        })
    }

    pub fn require_api_key(&self) -> Result<&str> {
        self.api_key
            .as_deref()
            .context("Not authenticated. Run `app-dist login` first.")
    }

    #[allow(dead_code)]
    pub fn project_config_exists(&self) -> bool {
        self.config_path.exists()
    }

    pub fn read_project_config(&self) -> Result<String> {
        std::fs::read_to_string(&self.config_path)
            .context("No app-dist.yml found. Run `app-dist setup signing` or create one manually.")
    }
}

pub fn get_keychain_key() -> Result<String> {
    let entry = keyring::Entry::new(SERVICE_NAME, KEYCHAIN_USER)?;
    entry.get_password().context("No API key found in Keychain")
}

pub fn set_keychain_key(key: &str) -> Result<()> {
    let entry = keyring::Entry::new(SERVICE_NAME, KEYCHAIN_USER)?;
    entry.set_password(key)?;
    Ok(())
}

#[allow(dead_code)]
pub fn delete_keychain_key() -> Result<()> {
    let entry = keyring::Entry::new(SERVICE_NAME, KEYCHAIN_USER)?;
    entry.delete_credential()?;
    Ok(())
}

pub async fn setup_signing() -> Result<()> {
    println!("{}", "Setting up Apple signing credentials".bold());
    println!();

    let detected_team = detect_team_id();

    let team_id = dialoguer::Input::<String>::new()
        .with_prompt("Apple Developer Team ID")
        .default(detected_team.unwrap_or_default())
        .interact()?;

    if team_id.is_empty() {
        anyhow::bail!("Team ID is required. Find it in Xcode > Settings > Accounts.");
    }

    let notary_profile = dialoguer::Input::<String>::new()
        .with_prompt("notarytool keychain profile name")
        .default("app-dist-notary".to_string())
        .interact()?;

    let mut has_api_key = false;
    let auth_key_id: String = dialoguer::Input::<String>::new()
        .with_prompt("App Store Connect API Key ID (or enter to skip)")
        .allow_empty(true)
        .interact()?;

    let mut auth_issuer_id = String::new();
    let mut auth_key_path = String::new();

    if !auth_key_id.is_empty() {
        has_api_key = true;
        auth_issuer_id = dialoguer::Input::<String>::new()
            .with_prompt("Issuer ID")
            .interact()?;

        auth_key_path = dialoguer::Input::<String>::new()
            .with_prompt("Path to .p8 key file")
            .default("~/.keys/AuthKey.p8".to_string())
            .interact()?;
    }

    let scheme = dialoguer::Input::<String>::new()
        .with_prompt("Xcode scheme name")
        .interact()?;

    let project = dialoguer::Input::<String>::new()
        .with_prompt("Xcode project path (e.g. MyApp.xcodeproj)")
        .interact()?;

    let bundle_id = dialoguer::Input::<String>::new()
        .with_prompt("Bundle identifier (e.g. com.example.MyApp)")
        .allow_empty(true)
        .interact()?;

    let config_content = format!(
        r#"# app-dist project configuration
# Generated by `app-dist setup signing`

app: "{}"
bundle_id: "{}"
channel: beta
xcode_project: "{}"
scheme: "{}"
archive_path: build/{}.xcarchive
signing:
  team_id: "{}"
  notarytool_profile: "{}"
{}sparkle:
  enabled: false
"#,
        slugify(&scheme),
        bundle_id,
        project,
        scheme,
        scheme,
        team_id,
        notary_profile,
        if has_api_key {
            format!(
                "  auth_key_id: \"{}\"\n  auth_issuer_id: \"{}\"\n  auth_key_path: \"{}\"\n",
                auth_key_id, auth_issuer_id, auth_key_path
            )
        } else {
            String::new()
        },
    );

    let config_path = std::env::current_dir()?.join("app-dist.yml");
    std::fs::write(&config_path, &config_content)?;
    println!();
    println!(
        "{} Wrote config to {}",
        "✓".green().bold(),
        config_path.display()
    );

    if has_api_key {
        println!();
        println!("{} Add this to your .gitignore:", "Note:".yellow());
        println!("  app-dist.yml");
    }

    println!();
    println!(
        "{} Next step: create your app on the platform",
        "→".dimmed()
    );
    println!("  app-dist app create --name \"{}\"", scheme);

    Ok(())
}

fn detect_team_id() -> Option<String> {
    let output = std::process::Command::new("security")
        .args(["find-identity", "-v", "-p", "codesigning"])
        .output()
        .ok()?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    for line in stdout.lines() {
        if line.contains("Developer ID") {
            if let Some(paren_start) = line.find('(') {
                if let Some(paren_end) = line[paren_start..].find(')') {
                    let id = line[paren_start + 1..paren_start + paren_end].trim();
                    if id.len() == 10
                        && id
                            .chars()
                            .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
                    {
                        return Some(id.to_string());
                    }
                }
            }
        }
    }
    None
}

fn slugify(input: &str) -> String {
    input
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_slugify_basic() {
        assert_eq!(slugify("My App"), "my-app");
    }

    #[test]
    fn test_slugify_empty() {
        assert_eq!(slugify(""), "");
    }

    #[test]
    fn test_slugify_special_chars() {
        assert_eq!(slugify("Hello!!! World???"), "hello-world");
    }

    #[test]
    fn test_slugify_consecutive_hyphens() {
        assert_eq!(slugify("a--b---c"), "a-b-c");
    }

    #[test]
    fn test_slugify_leading_trailing() {
        assert_eq!(slugify("---Hello---"), "hello");
    }

    #[test]
    fn test_slugify_numbers() {
        assert_eq!(slugify("App 2.0"), "app-2-0");
    }

    #[test]
    fn test_detect_team_id_valid() {
        let line = "  1) ABCD123456 \"Developer ID Application: Team Name (ABCD123456)\"";
        assert_eq!(
            detect_team_id_from_line(line),
            Some("ABCD123456".to_string())
        );
    }

    #[test]
    fn test_detect_team_id_no_developer_id() {
        let line = "  1) ABCD123456 \"Apple Development: some@icloud.com (ABCD123456)\"";
        assert_eq!(detect_team_id_from_line(line), None);
    }

    #[test]
    fn test_detect_team_id_wrong_length() {
        let line = "  1) ABC \"Developer ID Application: Team (ABC)\"";
        assert_eq!(detect_team_id_from_line(line), None);
    }

    fn detect_team_id_from_line(line: &str) -> Option<String> {
        if !line.contains("Developer ID") {
            return None;
        }
        let paren_start = line.find('(')?;
        let paren_end = line[paren_start..].find(')')?;
        let id = line[paren_start + 1..paren_start + paren_end].trim();
        if id.len() == 10
            && id
                .chars()
                .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
        {
            return Some(id.to_string());
        }
        None
    }

    #[test]
    fn test_config_load_with_override() {
        let cfg = Config::load(Some("https://custom.api.com")).unwrap();
        assert_eq!(cfg.api_url, "https://custom.api.com");
    }

    #[test]
    fn test_config_load_default() {
        unsafe { std::env::remove_var("APP_DIST_API_URL") };
        let cfg = Config::load(None).unwrap();
        assert_eq!(cfg.api_url, "https://api.app-dist.com");
    }

    #[test]
    fn test_config_require_api_key_none() {
        let cfg = Config {
            api_url: "https://test.com".to_string(),
            api_key: None,
            config_path: std::path::PathBuf::from("/tmp/test"),
        };
        assert!(cfg.require_api_key().is_err());
    }

    #[test]
    fn test_config_require_api_key_some() {
        let cfg = Config {
            api_url: "https://test.com".to_string(),
            api_key: Some("apd_test".to_string()),
            config_path: std::path::PathBuf::from("/tmp/test"),
        };
        assert_eq!(cfg.require_api_key().unwrap(), "apd_test");
    }
}
